version: '3.8'

services:
  mcp-server-chart:
    image: ghcr.io/luxizai/mcp-server-chart-docker:latest
    command: ["node", "build/index.js", "--transport", "sse", "--port", "1122", "--endpoint", "/sse"]
    ports:
      - "1122:1122"
    environment:
      - NODE_ENV=production
      # 可选：自定义图表生成服务
      # - VIS_REQUEST_SERVER=https://your-custom-vis-server.com/api/gpt-vis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:1122/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
