services:
  mcp-server-chart:
    image: ghcr.io/luxizai/mcp-server-chart-docker:latest
    ports:
      - "1122:1122"
    restart: always
    volumes:
      - ./streamable:/mcp-server-chart/streamable
